version: '3.8'
services:
  api:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=mssql
      - DB_PORT=1433
      - DB_USERNAME=sa
      - DB_PASSWORD=YourPassword123
      - DB_DATABASE=master
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: 'YourPassword123'
      ACCEPT_EULA: 'Y'
    ports:
      - '1433:1433'
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
